!HOW MANY A HAS IN A STRING
PROGRAM NO_OF_A_IN_STRING
 IMPLICIT NONE
 CHARACTER(LEN=100)::STRING,TEMP
 INTEGER::I,J,STRING_LEN,C=0
 PRINT*,"ENTER A STRING:TO END THE STRING BY TYPING SPACE WITH ENTER"
  READ 10,STRING
 10 FORMAT(A100)

 STRING=TRIM(STRING)
 STRING_LEN=LEN_TRIM(STRING)
DO I=1,STRING_LEN
 IF( STRING(I:I) == "A" .OR. STRING(I:I) == "a" ) THEN
  C=C+1
 ENDIF
END DO

PRINT*,"TOTAL NO OF A IS=",C
END PROGRAM NO_OF_A_IN_STRING
